---
version: "3.8"
services:
  # @todo #169 Create application container. This image should be
  #  self-contain installation which is able to run all scripts to
  #  rule them all. Things like documentation generator & local PDD
  #  tool should be available inside the image.
  database:
    image: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=limebot
      - POSTGRES_USER=limebot
      - POSTGRES_PASSWORD=limebot
  cache:
    image: redis
    volumes:
      - cache_data:/data
volumes:
  database_data:
  cache_data:
