#!/bin/bash -e

poetry run coverage run -m pytest
poetry run coverage report --fail-under 100
poetry run pre-commit run -a
poetry run black --check .
poetry run flake8 .
poetry run bellybutton lint
npx jscpd src/
npx eslint --ext .js,.json --ignore-path .gitignore .
