#!/bin/bash -e

poetry run coverage run -m pytest
poetry run coverage report --fail-under 100
poetry run pre-commit run -a
git ls-files '*.py' | xargs poetry run pyupgrade --py38-plus
git ls-files '*.py' | xargs docformatter --wrap-summaries 88 --wrap-descriptions 88 --blank --check
poetry run black --check .
poetry run flake8 .
poetry run bellybutton lint
poetry run bandit -r .
poetry run xenon --max-absolute A --max-modules A --max-average A --ignore node_modules .
poetry run yamllint --strict .
npx jscpd src/
npx eslint --ext .js,.json --ignore-path .gitignore .
